### ISSUE TITLE
pip install -r requirements.txt fails on Windows

### ISSUE THREAD

**Issue by FranckDemanou** [openassistant/oa-core#25] opened 2019-12-02 14:00 UTC
I've become this error:

  Running setup.py install for pocketsphinx ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\python\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\franc\\AppData\\Local\\Temp\\pip-install-7p1u8a4n\\pocketsphinx\\setup.py'"'"'; __file__='"'"'C:\\Users\\franc\\AppData\\Local\\Temp\\pip-install-7p1u8a4n\\pocketsphinx\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\franc\AppData\Local\Temp\pip-record-j0tp8_pa\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\franc\AppData\Local\Temp\pip-install-7p1u8a4n\pocketsphinx\
    Complete output (6 lines):
    running install
    running build_ext
    building 'sphinxbase._sphinxbase' extension
    swigging deps/sphinxbase/swig/sphinxbase.i to deps/sphinxbase/swig/sphinxbase_wrap.c
    swig.exe -python -modern -threads -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -Ideps/sphinxbase/include/win32 -Ideps/sphinxbase/swig -outdir sphinxbase -o deps/sphinxbase/swig/sphinxbase_wrap.c deps/sphinxbase/swig/sphinxbase.i
    error: command 'swig.exe' failed: No such file or directory
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\franc\\AppData\\Local\\Temp\\pip-install-7p1u8a4n\\pocketsphinx\\setup.py'"'"'; __file__='"'"'C:\\Users\\franc\\AppData\\Local\\Temp\\pip-install-7p1u8a4n\\pocketsphinx\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\franc\AppData\Local\Temp\pip-record-j0tp8_pa\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

I need help to fix it, thanks.

**Comment by joshuashort** [comment] 2019-12-02 19:35
You're missing `swig.exe`, so install that however it's done on Windows. There are probably other missing system dependencies, but this hasn't been mapped/documented.

**Comment by joshuashort** [comment] 2020-01-27 08:00
Added some notes to https://github.com/openassistant/oa-core/wiki/Installation#windows

This is the same kind of problem as #22

Closing this issue for now..

**Closed as completed by joshuashort** 2020-01-27 08:00 UTC

**Comment by pwab** [comment] 2020-05-26 09:51
The problem here is python's `pocketsphinx`. I tried the installation process with Python 3.9a, 3.8-stable and 3.7.x on conda. I encountered the same problem and it finally leads to the problem that pocketsphinx isn't build for python versions above 3.6 (no wheels available).

See https://github.com/bambocher/pocketsphinx-python/issues/49 for reference.

This is not a bug of OA. But it could be documented that:

- You have to use python 3.x up to 3.6 if you want to use pip
- You could compile pocketsphinx yourself (but I have no clue how this is done)
